alias ls='ls --color=auto'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias fucking='sudo'
alias c='clear'
alias vpnus='sudo openvpn /etc/openvpn/client/usproton.conf'
alias vpnnl='sudo openvpn /etc/openvpn/client/nlproton.conf'
alias vpn='sudo protonvpn-cli -connect'
alias vpn-off='sudo protonvpn-cli -disconnect'
